steps:
  # Install deps and build
  - name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm ci
        npm run build

  # Deploy to VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp --recurse dist/* painbonanza-web:/tmp/site/ --zone=us-central1-a --quiet
        gcloud compute ssh painbonanza-web --zone=us-central1-a --quiet --command="sudo cp -r /tmp/site/* /var/www/html/ && sudo chown -R deploy:www-data /var/www/html"

options:
  logging: CLOUD_LOGGING_ONLY
